version: "3.7"
networks:
  jenkins:

services:
  jenkins:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        USER: cuong
        GROUP: cuong
        UID: 1000
        GID: 1000
        HTTP_PORT: 8080
        AGENT_PORT: 50000
        JENKINS_VERSION: 2.277.2
        JENKINS_SHA: 423d506cbfccf677a8f8112e170e611d65a49244b0ca87d2b134dd3ecb2e9b22
        JENKINS_HOME: /home/cuong/jenkins_home
        TZ: ASIA/Ho_Chi_Minh
        DEBIAN_FRONTEND: noninteractive
    image: hungcuongvt90/jenkins:ubuntu-jenkins-2.277.2-cuong
    container_name: jenkins
    user: cuong
    expose:
      - 8080
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - ${PWD}/../jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - jenkins
    restart: always
