version: "3.7"
networks:
  jenkins:

services:
  jenkins:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        USER: dev
        GROUP: dev
        UID: 1000
        GID: 1000
        HTTP_PORT: 8080
        AGENT_PORT: 50000
        JENKINS_VERSION: 2.277.1
        JENKINS_SHA: 399741db1152ee7bbe8dc08e0972efa0b128a1b55a0f8b10c087fefeec66d151
        JENKINS_HOME: /home/dev/jenkins_home
        TZ: ASIA/Ho_Chi_Minh
        DEBIAN_FRONTEND: noninteractive
    image: hungcuongvt90/jenkins:ubuntu-jenkins-2.277.1
    container_name: jenkins
    user: dev
    expose:
      - 8080
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - ${PWD}/../jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - jenkins
    restart: always
