version: "3.7"
networks:
  jenkins:

services:
  jenkins:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        USER: cuong
        GROUP: cuong
        UID: 1000
        GID: 1000
        HTTP_PORT: 8080
        AGENT_PORT: 50000
        JENKINS_VERSION: 2.289.1
        JENKINS_SHA: 70f9cc6ff1ac59aeeb831b980709a9ddb0ee70d216ee50625a8508b9840f75f2
        JENKINS_HOME: /home/cuong/jenkins_home
        TZ: ASIA/Ho_Chi_Minh
        DEBIAN_FRONTEND: noninteractive
    image: hungcuongvt90/jenkins:ubuntu-jenkins-2.289.1-cuong
    container_name: jenkins
    user: cuong
    expose:
      - 8080
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - ${PWD}/../jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - jenkins
    restart: always
