version: "3.7"
networks:
  jenkins:

services:
  jenkins:
    build:
      context: .
      dockerfile: Dockerfile-alpine
      args:
        USER: cuong
        GROUP: cuong
        UID: 1000
        GID: 1000
        HTTP_PORT: 8080
        AGENT_PORT: 40000
        JENKINS_VERSION: 2.263.1
        JENKINS_SHA: 
        SHA-256: 0eedeb2b11a32726acb57db26e262b1923cf408e84708baf471e3b53462ed6f1
        JENKINS_HOME: /home/cuong/jenkins_home
    image: smalldragonvt/jenkins:alpine-jenkins-2.263.1
    container_name: jenkins
    user: cuong
    expose:
      - 8080
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - ${PWD}/../jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - jenkins
    restart: always
